# Generated by Django 3.0.5 on 2020-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastamp',
            name='humidity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='datastamp',
            name='pressure',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='datastamp',
            name='rain_1h',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
