# Generated by Django 3.0.5 on 2020-05-19 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_station_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastamp',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastamp',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
