# Generated by Django 3.0.5 on 2020-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200519_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
