# Generated by Django 3.0.5 on 2020-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_station_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
