# Generated by Django 3.0.5 on 2020-05-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_station_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='is_verified',
        ),
    ]
